### ISSUE TITLE
Prop being mutated: "post" 

### ISSUE THREAD

**Issue by madmax124** [sanatorium/wp-vue-boilerplate#2]
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "post" 
(found in component <Post> at \src\post.vue)

**Comment by rozklad** [comment]
Hi,

thanks for reporting!

That should now be fixed by 573ec10e05fd0fb4b81be40b2c5304c9c2e3789 along with some other minor improvements on post.
